{
  viewer {
    repositoriesContributedTo(first: 100, contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]) {
      totalCount
      nodes {
        nameWithOwner, visibility
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}