name: Run main script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run_main_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run main script using github actions token
        run: |
          python main.py --token ${{ secrets.GH_TOKEN }}


      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results

      - name: Deploy the pdf file
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./results
          publish_branch: gh-pages
          force_orphan: true