name: Run main script

on:
  workflow_dispatch:

jobs:
  run_main_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run main script using github actions token
        run: |
          python main.py --token ${{ secrets.GH_TOKEN }}

      - name: Push all csv files to repo in a empty branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout --orphan gh-pages
          git rm -rf .
          git add *.csv
          git commit -m "Add csv files"
          git push origin gh-pages
      