name: Run main script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run_main_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run main script using github actions token
        run: |
          python main.py --token ${{ secrets.GH_TOKEN }}

      - name: Push all csv files to repo in a gh-pages branch without history

        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b gh-pages
          git add .
          git commit -m "Update csv files"
          git push origin gh-pages --force
          
      